version: '3.7'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    restart: always
    volumes:
      - uptime-kuma-data:/app/data
    environment:
      - TZ=UTC
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"

      traefik.http.routers.uptime.entrypoints: "web"
      traefik.http.routers.uptime.rule: "Host(`uptime.mathijsnabbe.nl`)"
      traefik.http.routers.uptime.service: "uptime-svc"
      traefik.http.services.uptime-svc.loadbalancer.server.port: 3001

volumes:
  uptime-kuma-data:

networks:
  traefik:
    external: true