version: '3'

networks:
  traefik:
    external: true

volumes:
  traefik-ssl-certs:
    driver: local
    
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - traefik-ssl-certs:/ssl-certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/mahnabbe/secrets/transip.pem:/transip.pem:ro
    networks:
      - traefik
    restart: unless-stopped
    environment:
      - TRAEFIK_GLOBAL_CHECKNEWVERSION=true
      - TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE=false
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_API_DISABLEDASHBOARDAD=true
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false

      - TRANSIP_ACCOUNT_NAME=mahnabbe
      - TRANSIP_PRIVATE_KEY_PATH=/transip.pem

      - TRAEFIK_CERTIFICATESRESOLVERS.transip.ACME.EMAIL=${EMAIL}
      - TRAEFIK_CERTIFICATESRESOLVERS.transip.ACME.STORAGE=/acme.json
      - TRAEFIK_CERTIFICATESRESOLVERS.transip.ACME.DNSCHALLENGE.PROVIDER=transip
      - TRAEFIK_CERTIFICATESRESOLVERS.transip.ACME.DNSCHALLENGE.DELAYBEFORECHECK=0
      - TRAEFIK_CERTIFICATESRESOLVERS.transip.ACME.DNSCHALLENGE.DISABLEPROPAGATIONCHECK=false

      - TRAEFIK_ENTRYPOINTS_web=true
      - TRAEFIK_ENTRYPOINTS_web_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_TO=websecure
      - TRAEFIK_ENTRYPOINTS_web_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME=https

      - TRAEFIK_ENTRYPOINTS_websecure=true
      - TRAEFIK_ENTRYPOINTS_websecure_ADDRESS=:443
      
      - TRAEFIK_ENTRYPOINTS_minecraft=true
      - TRAEFIK_ENTRYPOINTS_minecraft_ADDRESS=:25565
      
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"

      traefik.http.routers.traefik.rule: "Host(`dashboard.mathijsnabbe.nl`)"
      traefik.http.routers.traefik.entrypoints: "websecure"
      traefik.http.routers.traefik.tls: "true"
      traefik.http.routers.traefik.tls.certresolver: "transip"
      traefik.http.routers.traefik.service: "traefik-svc"
      traefik.http.services.traefik-svc.loadbalancer.server.port: 8080

