version: '3.8'

services:
  github-runner:
    image: my-github-runner:latest
    container_name: github-runner
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REPO_URL: ${RUNNER_URL}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_NAME: ${RUNNER_NAME}
    restart: unless-stopped
    volumes:
      - runner-data:/home/runner/_work
      - ./runner:/home/runner
    user: "runner:runner"

volumes:
  runner-data:
