services:
  github-runner:
    build: .
    container_name: github-runner
    environment:
      - REPO_URL=https://github.com/MathijsNabbe/Digital-CV
      - RUNNER_TOKEN=AKDRG3FXHJCAXAM4JROHIDTH67FNY 
    restart: unless-stopped

volumes:
  runner-data:
