services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    ports:
      - "25565:25565"
      - "8123:8123"
    environment:
      EULA: "TRUE"
      INIT_MEMORY: "1G"
      MEMORY: "4G"
      MAX_MEMORY: "6G"
      DIFFICULTY: "normal"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      FORCE_GAMEMODE: "true"
      GENERATE_STRUCTURES: "true"
      MAX_BUILD_HEIGHT: "500"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      SPAWN_PROTECTION: "0"
      MODE: "survival"
      PVP: "false"
      LEVEL_TYPE: "normal"
      ONLINE_MODE: "true"
      ALLOW_FLIGHT: "true"
      SERVER_NAME: "Piemelepenis"

      TYPE: "FORGE"
      VERSION: "1.20.1"

      CF_FORCE_REINSTALL_MODLOADER: true

    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"

      traefik.http.routers.minecraft.entrypoints: "minecraft"
      traefik.http.routers.minecraft.rule: "Host(`mc.mathijsnabbe.nl`)"


      traefik.http.routers.dynmap.entrypoints: "web"
      traefik.http.routers.dynmap.rule: "Host(`maps.mc.mathijsnabbe.nl`)"
      traefik.http.routers.dynmap.service: "dynmap-svc"
      traefik.http.services.dynmap-svc.loadbalancer.server.port: 8123

    networks:
      - traefik
      
    volumes:
      - /home/mahnabbe/gamedata/minecraft/data:/data

networks:
  traefik:
    external: true
      
